[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.pylint.format]
max-line-length = 120

[tool.mypy]
warn_return_any = true
warn_unused_configs = true

#[tool.pylint.messages_control]
#disable = ["C0114", "C0115", "C0116"]  # Skip some docstring warnings