[tool.black]
line-length = 125
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | venv
  | _build
  | buck-out
  | build
  | dist
  | assets
)/
'''

[tool.isort]
profile = "black"
line_length = 125
skip_gitignore = true
skip_glob = ["venv/*", ".venv/*"]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.flake8]
max-line-length = 125
extend-ignore = ["E203", "E501", "E701", "W503"]
exclude = [".git", "__pycache__", "dist", "assets", "venv", ".venv"]
per-file-ignores = [
    "__init__.py:F401",  # Allow unused imports in __init__.py files
]